language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - pypy
cache: pip
install:
  - pip install tox-travis
matrix:
  fast_finish: true
script:
  - tox
after_success:
  - curl -Lo travis_after_all.py https://git.io/travis_after_all
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - |
      if [ "$BUILD_LEADER" = "YES" ]; then
        if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
          python setup.py coverage && codecov
        fi
      fi
