language: python
env:
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
  - TOXENV=lint
  - TOXENV=pre-commit
cache: pip
install:
  - if [ "$TOXENV" = "lint" ]; then pip install pylint; fi
  - if [ "$TOXENV" != "lint" -a "$TOXENV" != "pre-commit" ]; then pip install -r requirements-dev.txt; fi
  - if [ "$TOXENV" = "pre-commit" ]; then
      pip install pre-commit;
      pre-commit install;
    fi
matrix:
  fast_finish: true
script:
  - if [ "$TOXENV" = "lint" ]; then pylint --rcfile=.pylintrc -E tableau_parser; fi
  - if [ "$TOXENV" != "lint" -a "$TOXENV" != "pre-commit" ]; then python setup.py test; fi
  - if [ "$TOXENV" = "pre-commit" ]; then pre-commit run --all-files; fi
after_success:
  - curl -Lo travis_after_all.py https://git.io/travis_after_all
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - |
      if [ "$BUILD_LEADER" = "YES" ]; then
        if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
          python setup.py coverage && codecov
        fi
      fi
